name: superso_dart
description: Dart SDK for Superso Backend Services.
version: 1.0.3

homepage: https://github.com/abdullahiissacksheikh-max/superso_dart
repository: https://github.com/abdullahiissacksheikh-max/superso_dart
issue_tracker: https://github.com/abdullahiissacksheikh-max/superso_dart/issues

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  shared_preferences: ^2.5.5
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter: